---
- name: Step 005 Post Software
  hosts: localhost
  become: false
  gather_facts: false
  tags:
    - step005
    - post_software
  tasks:
    - debug:
      msg: "Step 005 Post Software"

    - name: Add AWS sandbox credentials if enabled
      when:
      - cloud_provider == 'ec2'
      block:
      - name: Set facts for AWS credentials
        set_fact:
          student_access_key_id: "{{ cloudformation_out_final.stack_outputs.StudentUserAccessKey }}"
          student_secret_access_key: "{{ cloudformation_out_final.stack_outputs.StudentUserSecretAccessKey }}"
      
      - name: Add AWS credentials with agnosticd_user_info
        agnosticd_user_info:
          msg: "{{ item }}"
          data:
            aws_access_key_id: "{{ student_access_key_id }}"
            aws_secret_access_key: "{{ student_secret_access_key }}"
            aws_subdomain_base_suffix: "{{ subdomain_base_suffix }}"
          loop:
            - "aws_access_key_id: {{ student_access_key_id }}"
            - "aws_secret_access_key: {{ student_secret_access_key }}"
            - "aws_sandbox_zone: {{ subdomain_base_suffix }}"

    - name: Print string expected by Cloudforms
      debug:
        msg: "Post-Software checks completed successfully"
