---
become_override: False
ocp_username: jfalkner-redhat.com
silent: False

ocp4_workshop_quarkus_workshop_user_che_user_password: 'openshift'
ocp4_workshop_quarkus_workshop_user_openshift_user_password: 'openshift'

ocp4_workshop_quarkus_workshop_user_module_titles:
  m1:
    title: "Basic Quarkus Development"
    path: "/workshop/quarkus-lab/lab/intro"
  m2:
    title: "Advanced Quarkus Development"
    path: "/workshop/quarkus-lab/lab/extensions"
  m3:
    title: "Spring to Quarkus Modernization"
    path: "/workshop/quarkus-lab/lab/springweb"
