---
become_override: False
ocp_username: jfalkner-redhat.com
silent: False

workshop_openshift_user_password: 'openshift'
workshop_che_user_password: 'openshift'
workshop_openshift_admin_password: 'r3dh4t1!'

