---
- name: Verify everything is deployed correctly
  include_tasks: verify-workload.yaml

# Implement your Post Workload deployment tasks here

- name: Print user info
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
  - "{{ ocp_username }} has been setup on the shared lab environment."
  - "You have access to the following project: {{ guid }}-project"
  - ""
  - "OpenShift Console: {{ console_url }}"
  - "CodeReady Console: https://codeready-codeready.{{ route_subdomain }}"
  - ""

- name: Print module info
  agnosticd_user_info:
    msg: "Module {{item}}: http://web-{{item}}-guides.{{ route_subdomain }}"
  loop: "{{ modules }}"

- name: Save user data
  agnosticd_user_info:
    data:
      web_console_url: "{{ console_url }}"
      api_url: "{{ master_url }}"
      login_command: "oc login -u {{ ocp_username }} {{ master_url }}"

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
