---
# Implement your Pre Workload deployment tasks here

- name: Ensuring username is defined
  fail:
    msg: "This workload requires ocp_username to be defined. Exiting..."
  when: ocp_username is not defined

- name: Ensuring guid is defined
  fail:
    msg: "This workload requires guid to be defined. Exiting..."
  when: guid is not defined

# Figure out paths
- name: extract api_url
  command: oc whoami --show-server
  register: api_url_r

- name: set the master
  set_fact:
    master_url: "{{ api_url_r.stdout | trim }}"

- name: extract console_url
  command: oc whoami --show-console
  register: console_url_r

- name: set the console
  set_fact:
    console_url: "{{ console_url_r.stdout | trim }}"

- name: extract route_subdomain
  k8s_facts:
    kind: Ingress
  register: route_subdomain_r

- name: set the route
  set_fact:
    route_subdomain: "{{ route_subdomain_r.resources[0].spec.domain | trim }}"

- name: set bastion_fqdn
  set_fact:
    bastion_fqdn: "{{ subdomain_base }}"

- name: Get codeready keycloak deployment
  k8s_facts:
    kind: Deployment
    namespace: codeready
    name: keycloak
  register: r_keycloak_deployment

- name: show cr
  debug:
    msg: "existing keycloak deployment: {{ r_keycloak_deployment }}"

- name: set codeready username fact
  set_fact:
    codeready_sso_admin_username: "{{ r_keycloak_deployment.resources[0].spec.template.spec.containers[0].env | selectattr('name','equalto','SSO_ADMIN_USERNAME') |map (attribute='value') | list | first }}"

- name: set codeready password fact
  set_fact:
    codeready_sso_admin_password: "{{ r_keycloak_deployment.resources[0].spec.template.spec.containers[0].env | selectattr('name','equalto','SSO_ADMIN_PASSWORD') |map (attribute='value') | list | first }}"

- name: show codeready keycloak admin username
  debug:
    msg: "codeready keycloak admin username: {{ codeready_sso_admin_username }}"

- name: show codeready keycloak admin password
  debug:
    msg: "codeready keycloak admin password: {{ codeready_sso_admin_password }}"

- name: debug values
  debug:
    msg:
    - "master URL: {{ master_url }}"
    - "console URL: {{ console_url }}"
    - "route subdomain: {{ route_subdomain }}"
    - "ocp_username: {{ ocp_username }}"
    - "bastion host: {{ bastion_fqdn }}"

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool
